polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:pk>/', views.polls_edit, name='edit'),
    path('delete/<int:pk>/', views.polls_delete, name='delete_poll'),
    path('edit/<int:pk>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:pk>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:pk>/', views.choice_delete, name='choice_delete'),
    path('<int:pk>/', views.poll_detail, name='detail'),
    path('<int:pk>/vote/', views.poll_vote, name='vote'),
    path('<int:pk>/result/', views.poll_result, name='result'),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls', namespace="polls")),
]

polls/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
class Poll_question(models.Model):
    question_body = models.CharField(max_length=200)
    is_single = models.BooleanField(default=1, verbose_name="Single Choice")
    published_date = models.DateTimeField('Date Published', default=timezone.now)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.question_body
    
    def was_asked_recently(self):
        return self.published_date >= timezone.now() - datetime.timedelta(days=2)
    
    @property
    def get_vote_count(self):
        return self.individual_vote_set.count()
    
    def user_can_vote(self, user):
        user_votes = user.individual_vote_set.all()
        ques = user_votes.filter(question=self)
        if ques.exists():
            return False
        return True
    
    def get_result_dict(self):
        results = []
        for option in self.poll_option_set.all():
            d = {}
            d['text'] = option.option_body
            d['num_votes'] = option.get_vote_count
            if not self.get_vote_count:
                d['percentage'] = 0
            else:
                d['percentage'] = (option.get_vote_count / self.get_vote_count)*100
            results.append(d)
        return results
    
    class Meta:
        ordering = ['-published_date']
    
class Poll_option(models.Model):
    question = models.ForeignKey(Poll_question, on_delete=models.CASCADE)
    option_body = models.CharField(max_length=200)
    
    def __str__(self):
        return f"{self.question.question_body} - {self.option_body}"
    
    @property
    def get_vote_count(self):
        return self.individual_vote_set.count()
    

class Individual_vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Poll_question, on_delete=models.CASCADE)
    option = models.ForeignKey(Poll_option, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.question.question_body} - {self.option.option_body} - {self.user.username}'

polls/forms.py
from django import forms
from .models import Poll_question, Poll_option

class PollAddForm(forms.ModelForm):
    # choice1 = forms.CharField(label='Choice 1', max_length=100, min_length=1,
    #                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    # choice2 = forms.CharField(label='Choice 2', max_length=100, min_length=1,
    #                           widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Poll_question
        fields = ['question_body', 'is_single']
        widgets = {
            'question_body': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
        }


class EditPollForm(forms.ModelForm):
    class Meta:
        model = Poll_question
        fields = ['question_body', ]
        widgets = {
            'question_body': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
        }


class ChoiceAddForm(forms.ModelForm):
    class Meta:
        model = Poll_option
        fields = ['option_body', ]
        widgets = {
            'option_body': forms.TextInput(attrs={'class': 'form-control', })
        }

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from numpy import equal
from .models import Poll_question, Poll_option, Individual_vote
from .forms import PollAddForm, EditPollForm, ChoiceAddForm
from accounts.models import User_meta_data

@login_required()
def polls_list(request):
    all_questions = Poll_question.objects.all()
    user_meta = User_meta_data.objects.get(id=request.user.id)
    context = {
        'polls': all_questions,
        'media_icons': False,
        'user': user_meta
    }
    return render(request, 'polls/polls_list.html', context)

@login_required()
def list_by_user(request):
    all_questions = Poll_question.objects.filter(creator=request.user)
    user_meta = User_meta_data.objects.get(id=request.user.id)
    context = {
        'polls': all_questions,
        'media_icons': True,
        'user': user_meta
    }
    return render(request, 'polls/polls_list.html', context)


@login_required()
def polls_add(request):
    user_meta = User_meta_data.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = PollAddForm(request.POST)
        if form.is_valid:
            poll = form.save(commit=False)
            poll.creator = request.user
            poll.save()
            # Poll_option(question=poll, option_body=form.cleaned_data['choice1']).save()
            # Poll_option(question=poll, option_body=form.cleaned_data['choice2']).save()
            options = request.POST.getlist('options')
            print(options)
            for option in options:
                if option != "":
                    Poll_option(question=poll, option_body=option).save()
            messages.success(request, "Poll added successfully.")
            return redirect('polls:list')
    else:
        form = PollAddForm()
    context = {
        'form': form,
        'user': user_meta
    }
    return render(request, 'polls/add_poll.html', context)

@login_required
def polls_edit(request, pk):
    question = get_object_or_404(Poll_question, pk=pk)
    user_meta = User_meta_data.objects.get(id=request.user.id)
    if request.user != question.creator:
        return redirect('home')
    if request.method == 'POST':
        form = EditPollForm(request.POST, instance=question)
        if form.is_valid:
            form.save()
            return redirect("polls:list")
    else:
        form = EditPollForm(instance=question)
    return render(request, "polls/poll_edit.html", {'form': form, 'poll': question, 'user': user_meta})


@login_required
def polls_delete(request, pk):
    question = get_object_or_404(Poll_question, pk=pk)
    if request.user != question.creator:
        return redirect('home')
    question.delete()
    return redirect("polls:list")


@login_required
def add_choice(request, pk):
    user_meta = User_meta_data.objects.get(id=request.user.id)
    question = get_object_or_404(Poll_question, pk=pk)
    if request.user != question.creator:
        return redirect('home')
    if request.method == 'POST':
        form = ChoiceAddForm(request.POST)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.question = question
            new_choice.save()
            return redirect('polls:edit', question.id)
    else:
        form = ChoiceAddForm()
    context = {
        'form': form,
        'user': user_meta
    }
    return render(request, 'polls/add_choice.html', context)


@login_required
def choice_edit(request, pk):
    user_meta = User_meta_data.objects.get(id=request.user.id)
    option = get_object_or_404(Poll_option, pk=pk)
    question = get_object_or_404(Poll_question, pk=option.question.id)
    if request.user != question.creator:
        return redirect('home')
    if request.method == 'POST':
        form = ChoiceAddForm(request.POST, instance=option)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.question = question
            new_choice.save()
            return redirect('polls:edit', question.id)
    else:
        form = ChoiceAddForm(instance=option)
    context = {
        'form': form,
        'edit_choice': True,
        'choice': option,
        'user': user_meta
    }
    return render(request, 'polls/add_choice.html', context)


@login_required
def choice_delete(request, pk):
    option = get_object_or_404(Poll_option, pk=pk)
    question = get_object_or_404(Poll_question, pk=option.question.id)
    if request.user != question.creator:
        return redirect('home')
    option.delete()
    return redirect('polls:edit', question.id)


def poll_detail(request, pk):
    user_meta = User_meta_data.objects.get(id=request.user.id)
    question = get_object_or_404(Poll_question, pk=pk)
    owner = False
    if request.user == question.creator:
        owner = True
    if not question.user_can_vote(request.user):
        chosen_options = question.individual_vote_set.filter(user=request.user)
        options = []
        if len(chosen_options) > 1:
            messages.error(request, f"You already voted this poll! Your choices were:\n")
            for chosen_option in chosen_options:
                options.append(chosen_option.option.option_body)
                messages.error(request, f"%s" % (chosen_option.option.option_body))
        else:  
            for chosen_option in chosen_options:
                messages.error(request, f"You already voted this poll! Your choice was: ")
                messages.error(request, f"%s" % (chosen_option.option.option_body))
                options.append(chosen_option.option.option_body)
        return render(request, 'polls/poll_result.html', {'poll': question, 'choice': options, 'owner': owner, 'pk': pk, 'user': user_meta})
    loop_count = question.poll_option_set.count()
    context = {
        'poll': question,
        'loop_time': range(0, loop_count),
        'owner': owner,
        'pk': pk,
        'user': user_meta
    }
    return render(request, 'polls/poll_detail.html', context)


@login_required
def poll_vote(request, pk):
    user_meta = User_meta_data.objects.get(id=request.user.id)
    question = get_object_or_404(Poll_question, pk=pk)
    owner = False
    if request.user == question.creator:
        owner = True
    options_ids = request.POST.getlist('choice')
    if not question.user_can_vote(request.user):
        messages.error(request, "You already voted this poll!")
        return render(request, 'polls/poll_result.html', {'poll': question, 'owner': owner, 'pk': pk, 'user': user_meta})
    if len(options_ids) > 0:
        for option_id in options_ids:
            option = Poll_option.objects.get(id=option_id)
            vote = Individual_vote(user=request.user, question=question, option=option)
            vote.save()
        return render(request, 'polls/poll_result.html', {'poll': question, 'owner': owner, 'pk': pk, 'user': user_meta})
    else:
        messages.error(request, "No choice selected!")
        return redirect("polls:detail", pk)


@login_required
def poll_result(request, pk):
    user_meta = User_meta_data.objects.get(id=request.user.id)
    question = get_object_or_404(Poll_question, pk=pk)
    owner = False
    if request.user == question.creator:
        owner = True
    return render(request, 'polls/poll_result.html', {'poll': question, 'owner': owner, 'pk': pk, 'user': user_meta})

polls/templates/polls/add_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
            <h2>Update choice</h2>
            {% else %}
            <h2>Add new choice</h2>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                {% if edit_choice %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:choice_delete' choice.id %}" role="button" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                {% else %}
                <button type="submit" class="btn btn-primary">Add</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/add_poll.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row center">
    <div class="col-md-6 offset-md-3" style="background-color: rgba(255, 255, 255, 0.9);">
      <h2>Create new poll</h2>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
          {{ message }}
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      <form action="" method="POST">
        {% csrf_token %} {% for field in form %}
        <div class="form-group">
          {{ field.errors }} {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %} 
        <div class="appending_div">
        </div>
        Give Choices:
        <span class="fa fa-plus add" style="cursor: pointer"></span><br><br>
        <button type="submit" class="btn btn-primary">Add Poll</button>
        <a class="btn btn-warning" href="{% url 'polls:list' %}" role="button">
            Back
        </a>
      </form>
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    var i = 1;
    $(".add").on("click", function () {
      var field =
        "<div>Choice " +
        i +
        ': <input type="text" name="options" style="width: 100%;margin-bottom:1.2vw">';
      $(".appending_div").append(field);
      i = i + 1;
    });
  });
</script>
{% endblock %}

polls/templates/polls/endpoll.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <h3 class="mt-3 mb-3 text-center">
                Result for: {{ poll.question_body }}
            </h3>
            <div class="progress mt-3">
            {% for choice in poll.get_result_dict %}
            <div class="progress-bar" role="progressbar" style="width: {{ choice.percentage }}%;" aria-valuenow="30" aria-valuemin="0"
                aria-valuemax="100">
                {{ choice.text }} - {{ choice.percentage|floatformat }}%
            </div>
            {% endfor %}
        </div>
        <ul class="list-group">
            {% for choice in poll.poll_option_set.all %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ choice.text }}
                <span class="badge badge-primary badge-pill">
                    {{ choice.get_vote_count }}
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">
        Back To Polls
    </a>
</div>
{% endblock content %}

polls/templates/polls/poll_detail.html
{% extends 'base.html' %}
{% block custom_css %} 
<style>
    body{
        background-image: url('https://www.vevox.com/getmedia/bd789c97-3d31-4aa5-801c-a6d7d08af4ca/Meetoo_Header_600x200_ProductTraining_2-1.jpg');
        background-size: cover;
    }
</style>
{% endblock custom_css %}
{% block content %}
<div style="margin-top: 10vw;" class="container">
    <div class="col-md-8 offset-sm-2" style="padding-bottom:1.5vw;background-color: rgba(255, 255, 255, 0.95);">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <h1 class="text-center">Poll Details</h1>
        <hr>
        <h2 class="mt-3 mb-3">{{ poll }}</h2>
        <p>created by - <b>@{{ poll.creator }}</b></p>
        <form action="{% url 'polls:vote' poll.id %}" method="POST">
            {% csrf_token %}
            {% for choice in poll.poll_option_set.all %}
            {% if poll.is_single %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.option_body }}</label>
            {% else %}
            <input type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.option_body }}</label>
            {% endif %}
            <br>
            {% endfor %}
            <input type="submit" value="Vote" class="btn btn-primary mt-3">
            <a class="btn btn-warning mt-3" href="{% url 'polls:list' %}" role="button">Cancel</a>
        </form>
    </div>
    <div class="col-md-8 offset-sm-2">
        <br>
        <br>
    </div>
    {% if owner %}
        <div class="col-md-8 offset-sm-2 text-center" style="background-color: rgba(255, 255, 255, 0.95);">
            <h4>Share Your Polls on Social Media:</h4><br>
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Hi!! Vote on my Poll and see results of what others are thinking " data-url="http://127.0.0.1:8000/polls/{{pk}}" data-hashtags="polls,voting,makeyourvotecount" data-lang="en" data-show-count="false">
                Tweet
            </a>&nbsp&nbsp&nbsp&nbsp&nbsp
            <span id="fb-root"></span>
            <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>
            <div class="fb-share-button" data-text="Hi checkout this cool website!"
            data-href="http://127.0.0.1:8000/polls/{{pk}}" 
            data-layout="button">
            </div>&nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="https://www.linkedin.com/shareArticle?mini=true&url=http://127.0.0.1:8000/polls/{{pk}}&title=Hi!! Vote on my Poll and see results of what others are thinking&summary=http://127.0.0.1:8000/polls/{{pk}}&source=Pollsite" onclick="window.open(this.href, 'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" ><img src="https://chillyfacts.com/wp-content/uploads/2017/06/LinkedIN.gif" alt="" width="54" height="20" /></a>
            &nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="https://www.linkedin.com/shareArticle?mini=true&url=https://chillyfacts.com/create-linkedin-share-button-on-website-webpages&title=Create LinkedIn Share button on Website Webpages&summary=chillyfacts.com&source=Chillyfacts" onclick="window.open(this.href, 'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" ><img src="https://chillyfacts.com/wp-content/uploads/2017/06/LinkedIN.gif" alt="" width="54" height="20" /></a>
            &nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="https://api.whatsapp.com/send?text=Vote on my Poll: http://127.0.0.1:8000/polls/{{pk}}" data-action="share/whatsapp/share"><span style="font-size:1.5vw"><i class="fab fa-whatsapp-square"></span></i></a>
        </div>
        {% endif %}
</div>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8">
</script>
{% endblock content %}

polls/templates/polls/poll_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Edit poll</h2>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:delete_poll' poll.id %}" role="button" onclick="return confirm('Are you sure?')">Delete</a>
                <a class="btn btn-warning" href="{% url 'polls:add_choice' poll.id %}" role="button">Add Choice</a>
            </form>
            <div class="choices">
                <h2 class="text-center mt-3">Choices</h2>
                <hr>
                <ul class="list-group">
                    {% for choice in poll.poll_option_set.all %}
                    <li class="list-group-item">
                        <a href="{% url 'polls:choice_edit' choice.id %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                        </a>&nbsp
                        {{ choice.option_body }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/poll_result.html
{% extends 'base.html' %}
{% comment %} {% block custom_css %} 
<style>
    body{
        background-image: url('https://www.vevox.com/getmedia/bd789c97-3d31-4aa5-801c-a6d7d08af4ca/Meetoo_Header_600x200_ProductTraining_2-1.jpg');
        background-size: cover;
        z-index=-3;
    }
</style>
{% endblock custom_css %} {% endcomment %}
{% block content %}
<div class="container">
    <div class="row" style="margin-top:5vw;">
        <div class="col-md-8 offset-sm-2 text-center">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <h2 class="mt-3 mb-3 text-center">Result for: {{ poll.question_body }}</h2>
            <p>created by - <b>@{{ poll.creator }}</b></p>
            <h3 class="mb-2 text-center">Total: {{ poll.get_vote_count }} votes</h3>
            <ul class="list-group">
                {% for option in poll.get_result_dict %}
                <div style="width: 40vw;border-style: solid;border-color: white;border-radius: 5px;position: relative;">
                    <div style="height: 100%;position: absolute;top: 0px;left: 0px;z-index: -1;background-color: rgba(29, 155, 240, 0.6);width: {{option.percentage}}%;"></div>
                    <div style="position: absolute;top: 50%;right: 5px;transform: translate(0, -50%);">{{option.percentage|floatformat}}% ({{option.num_votes}})</div>
                    <div style="padding: 3px;width: 80%;text-align:left">{{option.text}}</div>
                </div>
                {% endfor %}
            </ul>
            <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">Back To Polls</a>
        </div>
        <div class="col-md-8 offset-sm-2">
            <br>
            <br>
        </div>
        {% if owner %}
        <div class="col-md-8 offset-sm-2 text-center" style="background-color: rgba(255, 255, 255, 0.9);">
            <h4>Share Your Polls on Social Media:</h4><br>
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Hi!! Vote on my Poll and see results of what others are thinking " data-url="http://127.0.0.1:8000/polls/{{pk}}" data-hashtags="polls,voting,makeyourvotecount" data-lang="en" data-show-count="false">
                Tweet
            </a>&nbsp&nbsp&nbsp&nbsp&nbsp
            <span id="fb-root"></span>
            <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>
            <div class="fb-share-button" data-text="Hi checkout this cool website!"
            data-href="http://127.0.0.1:8000/polls/{{pk}}" 
            data-layout="button">
            </div>&nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="https://www.linkedin.com/shareArticle?mini=true&url=http://127.0.0.1:8000/polls/{{pk}}&title=Hi!! Vote on my Poll and see results of what others are thinking&summary=http://127.0.0.1:8000/polls/{{pk}}&source=Pollsite" onclick="window.open(this.href, 'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" ><img src="https://chillyfacts.com/wp-content/uploads/2017/06/LinkedIN.gif" alt="" width="54" height="20" /></a>
            &nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="https://www.linkedin.com/shareArticle?mini=true&url=https://chillyfacts.com/create-linkedin-share-button-on-website-webpages&title=Create LinkedIn Share button on Website Webpages&summary=chillyfacts.com&source=Chillyfacts" onclick="window.open(this.href, 'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" ><img src="https://chillyfacts.com/wp-content/uploads/2017/06/LinkedIN.gif" alt="" width="54" height="20" /></a>
            &nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="https://api.whatsapp.com/send?text=Vote on my Poll: http://127.0.0.1:8000/polls/{{pk}}" data-action="share/whatsapp/share"><span style="font-size:1.5vw"><i class="fab fa-whatsapp-square"></span></i></a>
        </div>
        {% endif %}
    </div>
</div>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8">
</script>
{% endblock content %}

polls/templates/polls/polls_list.html
{% extends 'base.html' %}
{% block custom_css %} 
<style>
    body{
        background-image: url('https://www.vevox.com/getmedia/00b2a9e0-8835-418a-b6da-3c0d88b52cf8/Conferences-Events-Header-01.jpg');
        background-size: cover;
    }
</style>
{% endblock custom_css %}
{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-8 offset-sm-2" style="padding-bottom: 1vw;background-color: rgba(255, 255, 255, 0.9);">
            <h1 class="text-center mt-3 mb-3">Welcome to PollSite!</h1>
            <a class="btn btn-danger mb-3" href="{% url 'polls:add' %}" role="button">Add <i class="fas fa-plus"></i></a>
            <ul class="list-group">
                {% for poll in polls %}
                <li class="list-group-item">
                    <a href="{% url 'polls:detail' poll.id %}">
                        {{ poll.question_body|truncatewords:10 }}
                    </a>
                    {% if request.user == poll.creator %}
                    <a href="{% url 'polls:result' poll.id %}" data-toggle="tooltip" data-placement="top" title="Poll Result">
                        <i class="fas fa-poll float-right btn btn-danger btn-sm">
                        </i>
                    </a>
                    <a href="{% url 'polls:edit' poll.id %}" class="mr-3" data-toggle="tooltip" data-placement="top" title="Edit Poll">
                        <i class="fas fa-pencil-alt float-right btn btn-primary btn-sm mr-1">
                        </i>
                    </a>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock content %}