accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:pk>/', views.polls_edit, name='edit'),
    path('delete/<int:pk>/', views.polls_delete, name='delete_poll'),
    path('edit/<int:pk>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:pk>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:pk>/', views.choice_delete, name='choice_delete'),
    path('<int:pk>/', views.poll_detail, name='detail'),
    path('<int:pk>/vote/', views.poll_vote, name='vote'),
    path('<int:pk>/result/', views.poll_result, name='result'),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls', namespace="polls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Poll Site</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
      integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous"
    />
    <style>
      html,
      body {
        height: 100%;
        padding: 0.5vw;
      }
      #home-content {
        text-align: center;
        margin-top: 20%;
        background-color: rgba(255, 255, 255, 0.9);
        padding-bottom: 1vw;
      }
    </style>
    {% block custom_css %} {% endblock custom_css %}
  </head>

  <body>
    {% include 'navbar.html' %} {% block content %} {% endblock content%}
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} 
{% block custom_css %} 
<style>
    body{
        background-image: url('https://dornsife.usc.edu/assets/img/news/story/3338.jpg');
        background-size: cover;
    }
</style>
{% endblock custom_css %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <div id="home-content">
        <h1 style="font-size:5vw;">PollSite</h1>
        <hr />
        {% if logged_in %}
          <h4>Welcome, {{ user }}</h4><h6>You have {{count}} new Poll(s) to participate in.</h6> 
          <hr />
        {% endif %}
        <a class="btn btn-primary btn-lg" href="{% url 'polls:list' %}" role="button">
            Enter !!
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:list' %}">Polls</a>
            </li>
            {% endif %}
        </ul>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <p class="nav-link">Welcome {{user.first_name}}</p>
            <a class="nav-link" href="{% url 'polls:list_by_user' %}">My Polls</a>
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            {% endif %}
        </div>
    </div>
</nav>